In [ ]:
!pip install -q tensorflow-recommenders

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.2/96.2 kB 3.2 MB/s eta 0:00:00


In [ ]:
!pip install numpy==1.18.4

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 42.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  error: subprocess-exited-with-error
  
  × Building wheel for numpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects


In [ ]:
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import os
import pprint
import pandas as pd
import tempfile
from typing import Dict, Text
import numpy as np
import tensorflow as tf
import tensorflow_recommenders as tfrs

In [ ]:
class Config:

    embedding_dimension = 32

    model_path = "model.tf"

config = Config()

In [ ]:
# user data.
df = pd.read_csv('/content/data.csv')
# Features of job_interest.
jobs = pd.read_csv('/content/data2.csv')

In [ ]:
df["skills"] = df['skill_1'].astype(str) +", "+ df['skill_2'].astype(str) +", "+ df['skill_3'].astype(str) +", "+ df['skill_4'].astype(str)

In [ ]:
user = df[['id', 'name', 'skills', 'job_interest']]
user

id              name  \
0    AAJ603  Chris Westphalen   
1    HNA156      Koral Nilges   
2    FND122       Biron Mavin   
3    FMD294   Rurik Iwanowicz   
4    XVU891      Bobbee Foord   
..      ...               ...   
495  JCH211    Hendrika Amoss   
496  KWK881      Sile Watsham   
497  BUX671        Dolf Gavin   
498  EYD719   Linnea Houndsom   
499  UVX498    Kelvin Ansteys   

                                                skills  \
0    PHP, Visual Design, Google Cloud, Flutter Deve...   
1    Node.js, Information Architecture, Salesforce ...   
2    C#, Wireframing, Google Cloud, Flutter Develop...   
3    SQL, Usability Testing, DigitalOcean, Android ...   
4       Node.js, Wireframing, AWS, Flutter Development   
..                                                 ...   
495      React, Decision Trees, Xamarin, Digital Ocean   
496         Django, Classification, Java, Google Cloud   
497      HTML/CSS, Random Forest, Ionic, Alibaba Cloud   
498          Angular, Naive Bayes, Ionic, VMware Cloud   
499               C#, Regression, Swift, Alibaba Cloud   

                             job_interest  
0                          .NET Developer  
1                    Advance Data Analyst  
2                           AI Researcher  
3                       android architect  
4                       Android Developer  
..                                    ...  
495                          Web Designer  
496                         Web Developer  
497    Web Service Integration Specialist  
498         Windows Application Developer  
499  Wireless Network Security Specialist  

[500 rows x 4 columns]

In [ ]:
user = tf.data.Dataset.from_tensor_slices(dict(user))
jobs = tf.data.Dataset.from_tensor_slices(dict(jobs))

In [ ]:
# get the first rows of the job_interest dataset
for m in jobs.take(5):
  print(m)

{'id': <tf.Tensor: shape=(), dtype=string, numpy=b'xc1'>, 'job_interest': <tf.Tensor: shape=(), dtype=string, numpy=b'.NET Developer'>}
{'id': <tf.Tensor: shape=(), dtype=string, numpy=b'xc2'>, 'job_interest': <tf.Tensor: shape=(), dtype=string, numpy=b'Advance Data Analyst'>}
{'id': <tf.Tensor: shape=(), dtype=string, numpy=b'xc3'>, 'job_interest': <tf.Tensor: shape=(), dtype=string, numpy=b'AI Researcher'>}
{'id': <tf.Tensor: shape=(), dtype=string, numpy=b'xc4'>, 'job_interest': <tf.Tensor: shape=(), dtype=string, numpy=b'android architect'>}
{'id': <tf.Tensor: shape=(), dtype=string, numpy=b'xc5'>, 'job_interest': <tf.Tensor: shape=(), dtype=string, numpy=b'Android Developer'>}


In [ ]:
user = user.map(lambda x: {
    "id": x["id"],
    "name": x["name"],
    "job_interest": x["job_interest"]
})
jobs = jobs.map(lambda x: {
    "id": x["id"],
    "job_interest": x["job_interest"]})

In [ ]:
user_array = []
jobs_array = []
for data in user:
    user_array.append(data['id'].numpy().decode())
for data in jobs:
    jobs_array.append(data['job_interest'].numpy().decode())

#skills_array = tf.squeeze(skills).numpy().astype(str).tolist()
#jobs_array = tf.squeeze(jobs).numpy().astype(str).tolist()

user_ids_vocabulary = tf.keras.layers.StringLookup()
user_ids_vocabulary.adapt(user_array)

jobs_titles_vocabulary = tf.keras.layers.StringLookup()
jobs_titles_vocabulary.adapt(jobs_array)

In [ ]:
class JobLensModel(tfrs.Model):
  # We derive from a custom base class to help reduce boilerplate. Under the hood,
  # these are still plain Keras Models.

  def __init__(
      self,
      user_model: tf.keras.Model,
      jobs_model: tf.keras.Model,
      task: tfrs.tasks.Retrieval):
    super().__init__()

    # Set up user and job_interest representations.
    self.user_model = user_model
    self.jobs_model = jobs_model

    # Set up a retrieval task.
    self.task = task

  def compute_loss(self, features: Dict[Text, tf.Tensor], training=False) -> tf.Tensor:
    # Define how the loss is computed.

    user_embeddings = self.user_model(features["id"])
    jobs_embeddings = self.jobs_model(features["job_interest"])

    return self.task(user_embeddings, jobs_embeddings)

In [ ]:
# Define user and job_interest models.
user_model = tf.keras.Sequential([
    tf.keras.Input(shape=[], dtype=tf.string, name='id'),
    user_ids_vocabulary,
    tf.keras.layers.Embedding(user_ids_vocabulary.vocabulary_size(), 64)
])
jobs_model = tf.keras.Sequential([
    tf.keras.Input(shape=[], dtype=tf.string, name='job_interest'),
    jobs_titles_vocabulary,
    tf.keras.layers.Embedding(jobs_titles_vocabulary.vocabulary_size(), 64)
])

# Define your objectives.
task = tfrs.tasks.Retrieval(
    metrics=tfrs.metrics.FactorizedTopK(
        jobs.batch(128).map(jobs_model)
    )
)

/usr/local/lib/python3.10/dist-packages/keras/engine/functional.py:639: UserWarning: Input dict contained keys ['id'] which did not match any model input. They will be ignored by the model.
  inputs = self._flatten_to_reference_inputs(inputs)


In [ ]:
# Create a retrieval model.
model = JobLensModel(user_model, jobs_model, task)
model.compile(optimizer=tf.keras.optimizers.Adagrad(0.5))

# Train for 3 epochs.
model.fit(user.batch(4096), epochs=50)

Epoch 1/50
1/1 [==============================] - 1s 889ms/step - factorized_top_k/top_1_categorical_accuracy: 0.1100 - factorized_top_k/top_5_categorical_accuracy: 1.0000 - factorized_top_k/top_10_categorical_accuracy: 1.0000 - factorized_top_k/top_50_categorical_accuracy: 1.0000 - factorized_top_k/top_100_categorical_accuracy: 1.0000 - loss: 811.6653 - regularization_loss: 0.0000e+00 - total_loss: 811.6653
Epoch 2/50
1/1 [==============================] - 0s 84ms/step - factorized_top_k/top_1_categorical_accuracy: 0.1100 - factorized_top_k/top_5_categorical_accuracy: 1.0000 - factorized_top_k/top_10_categorical_accuracy: 1.0000 - factorized_top_k/top_50_categorical_accuracy: 1.0000 - factorized_top_k/top_100_categorical_accuracy: 1.0000 - loss: 811.6651 - regularization_loss: 0.0000e+00 - total_loss: 811.6651
Epoch 3/50
1/1 [==============================] - 0s 93ms/step - factorized_top_k/top_1_categorical_accuracy: 0.1100 - factorized_top_k/top_5_categorical_accuracy: 1.0000 - fact

In [ ]:
# Use brute-force search to set up retrieval using the trained representations.
index = tfrs.layers.factorized_top_k.BruteForce(model.jobs_model)
index.index_from_dataset(
    user.batch(100).map(lambda x: (x['id'], model.user_model(x['id'])))
)

# Get some recommendations.
ids = tf.constant(["xc12"])
_, titles = index(tf.constant(ids))
for i in range(len(ids)):
    print(f"Recommendations for user id {ids[i].numpy()}: {titles[i].numpy()}")

Recommendations for user id b'xc12': [b'KLM719' b'BKN910' b'BUX671' b'WYG144' b'PED490' b'UUK343' b'FUU412'
 b'XZG734' b'FND122' b'XLE736']


In [ ]:
def recommend(id):
    # Use brute-force search to set up retrieval using the trained representations.
    index = tfrs.layers.factorized_top_k.BruteForce(model.jobs_model)
    index.index_from_dataset(
        user.batch(100).map(lambda x: (x['id'], model.user_model(x['id'])))
    )

    # Get recommendations for the given user ID.
    ids = tf.constant([id])
    _, titles = index(tf.constant(ids))

    # Print the recommendations.
    recommendations = titles.numpy().tolist()
    return recommendations


In [ ]:
recommend('xc12')

[[b'KLM719',
  b'BKN910',
  b'BUX671',
  b'WYG144',
  b'PED490',
  b'UUK343',
  b'FUU412',
  b'XZG734',
  b'FND122',
  b'XLE736']]